use_frameworks!

platform :ios, '10.0'

target 'iOSHelper_Example' do
  pod 'iOSHelper', :path => '../'

  target 'iOSHelper_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
